import pymysql

db = pymysql.connect(
    host='okus.cz8dcgq2qxno.us-east-1.rds.amazonaws.com',
    user='pitech_master',
    password='HiKrKiNpOyS5ynHiKr',
    db='productionDummy')
cursor = db.cursor()

query = """
SELECT 
	S.email
FROM productionDummy.students S
where CONCAT(S.firstname,' ',S.lastname) like '%{0}%'
"""

student_names = [
    'Silana Gabriela Garcia',
    'Alan David Perez',
    'Xabiel Lluberes',
    'Annabelle Tarazona',
    'Carolina Ovalles',
    'Yann Sebastian Morency',
    'Wilthon Paulino',
    'Sara Massiel Segura',
    'Mariajose Soto',
    'Lia Karielys Torres',
    'Ariadna Hilario',
    'Marcos Consuegra',
    'Starlin David Herrera',
    'Eugenio Mena',
    'Emely Mena',
    'Lauren Dominguez',
    'Arsel Gonzalez',
    'Dana Jose Corcino',
    'Isamell Sanchez',
    'Sophia Carvajal',
    'Kelvin Vasquez',
    'Gabriela Bautista Santos',
    'Sarah Camila Francisco',
    'Daniel Estrella Ramos',
    'Matheu Batista Feliciano',
    'Dharled Loreley Batista',
    'Keyri Monserrat Matos',
    'Milagros Aquino ',
    'Sarah Santana Zabala',
    'Antonella Mateo',
    'Sarahi Gonzalez ',
    'Jesica Alejandra Santos',
    'Nazir Baez',
    'Angel Cruz Peguero',
    'Hector Guerrero ',
    'Abraham de Jesus ',
    'Elian Paulino',
    'Cesar Luis Santos',
    'Jean Carlos Mercado',
    'Jasmine Carolina Diaz',
    'Fernando Gabriel Tamayo',
    'Darwin Acosta Gonzalez',
    'Adrian Javier Martina',
    'Diego A. Bisono',
    'Alexander E. Bisino',
    'Omar Rodriguez',
    'Mell Marie Tapia',
    'Eric J. Veras',
    'Michael A. Perdomo',
    'Elianne A. Reyes',
    'Liliana Camila Castillo ',
    'Jean-lou Goris',
    'Shayrie Matos',
    'Sharlyn Matos Lopez',
    'Maria Jose Peña ',
    'Victor R. Mateo',
    'Sarah Kamila Perez ',
    'Adrian Javier Peguero',
    'S. Maximiliano Vera',
    'Emilio Valdez ',
    'Lia Camile Clime',
    'Luis Fernando Gonzalez',
    'Maria Fernanda Gonzalez',
    'Elisveth Feliz Torres',
    'Sahara Pichardo',
    'Juan A. Perez',
    'Emil M. Hernandez',
    'Emmanuel Polanco',
    'Diego Lorenzo',
    'Nicori Santiago',
    'Clarisa Santiago',
    'Dilany Hernandez',
    'Ernesto J. Ramirez',
    'Sarah Jimenez ',
    'Jana Yireh Liriano ',
    'Daniel Liriano Marte',
    'Valerie Corona',
    'Nelson Peguero',
    'Juan Isaac Reyes',
    'Edgar A. Garcia',
    'Selim Orlando Amargos',
    'Isaac D. Luciano',
    'Leah Kamille Henriquez',
    'Malik Zahir Britton ',
    'J. Jesus Mancebo',
    'Julio Jesus Mancebo',
    'Valerie N. Peralta',
    'Roxio A. Guillen',
    'Camila Mercedes Garcia',
    'Jose A. Nova',
    'Luis Enmanuel Pozo',
    'Pedro Ernesto Gaton',
    'Lia Marie Wellington',
    'Charlotte Marte Rosario',
    'Camila Marte Marte',
    'Victor G. Medina',
    'Erianny P. Soler',
    'Julio Cesar Rapozo',
    'Engel A. Martinez',
    'Gabriela Estevez',
    'Sairelys Molina',
    'Zulimar Reyes',
    'Elvin A. Inoa',
    'Leonardo Rojas',
    'Yassel A. Diaz',
    'Enmanuel Sanchez',
    'Dayra Smith',
    'Maria de los Angeles Liranzo',
    'Daniel I. Cuello ',
    'Lia Denisse Alvincola',
    'Daimely Elizabeth Alvincola Dominguez',
    'Armando J. Rodriguez',
    'Franchesca La Paix',
    'Alana D. Brito',
    'Ivana Z. Brito ',
    'Maria Valentina Torres',
    'Johao Martinez Lora',
    'Jesus. J. Capellan',
    'Ashely Isabelle Diaz',
    'Isabella Marie Diaz',
    'Gabriel Molina',
    'Fransisco Parra',
    'Mariangeles  Santana',
    'Luis Manuel Fiallo',
    'Nicole Marie Musa',
    'Andres Sabato',
    'Gael Brea ',
    'Adriana de la Rosa',
    'Isaura Sierra Soto',
    'Jose Angel Sierra Soto',
    'Sandy Abreu',
    'Stacy Carolina Diaz',
    'Diana Pancorbo',
    'Diego Pancorbo',
    'Amelia Rosario',
    'Sebastian Rosario',
    'Somer Jhulian Hernandez',
    'Gabriela Bautista Soriano',
    'Priscila Alejandra Bautista',
    'Maria Eugenia Ramon',
    'Kevin Emil Rodriguez',
    'Alexander Luciano',
    'Luis Manuel  Encinales Toribio',
    'Estrella Frias',
    'Rodrigo Alcantara ',
    'Mia Angelina Hernandez Calderon',
    'Naomy Amador',
    'Ricardo David Estrella',
    'Eduardo Estrella',
    'Rubi  Carvajal',
    'stella Marie Carvajal',
    'Emma G. Guzman',
    'Adlig Marie Guerrero Aquino',
    'Juan Andres Pardo',
    'Zamir Mancebo',
    'Keily Castro',
    'Yeily Castro ',
    'Roger Adriel Salcedo',
    'Fabio Tamayo',
    'Abel Maldonado',
    'Francisco de la Cruz ',
    'Alia Zayas Gil',
    'Amaia Zayas Gil',
    'Juan Carlos Serrano',
    'Angelica Sosa Rodriguez',
    'Radiel Castro',
    'Angelica Batista',
    'William Jadiel Perez',
    'Angie Manuela Alcantara',
    'Camila Guzman',
    'Avril Alcantara',
    'Carla Brea Paulino',
    'Jurgen Gustavo nunez',
    'Fabian Almonte ',
    'Carlos E. Cruz',
    'Kedzie  Jillian Nunez Perez',
    'Yamfred Amir Santana',
    'Yamilet Raquel Santana Cruz',
    'Amelia Paola  Alvarado Fernandez',
    'Lenny Javier Romero Moreno',
    'Arianna Lizbeth Cedeño',
    'Ivan Emmanuel Garrido Pujols',
    'Zoe Juliette Garrido Pujols',
    'Gabriela Alexandra Gomez',
    'Frank Gabriel Suero Canario',
    'Ramon Eduardo Garces Diaz',
    'Emmanuel A. Valdez Dominguez',
    'Alicia M. Bisono Ventura',
    'Jose Ysrael Santos Then',
    'Paula Sangiovanni',
    'Diego Muñoz ',
    'Jaime Elias Muñoz ',
    'Marcus Aurelio Marmolejos Arismendy',
    'Sarah Carolina Marmolejos Arismendy',
    'Alberto George Flores',
    'Tony Enmnuel Duran Rosa',
    'Lia Sophia Montero Ramirez',
    'Amanda Sencion Chevalier',
    'Victor Manuel Rodriguez Ruiz',
    'Luisa Virginia Diaz Blanco',
    'Jean Luis Diaz Blanco',
    'Maia M. Fanini Mercedes',
    'Grace Estevez',
    'Zoe Gissel',
    'Odile Berment',
    'Franklyn Yandiel Mejia ',
    'Sarah Graciano Vasquez',
    'Sebastian Olivo',
    'Luis A. Salomón ',
    'Chelsea Santos',
    'Ronald Santos',
    'Ian Jose Iglesias',
    'Jeremy Alexander  Seijas',
    'Angel Rafael Perez Aquino',
    'Luciana Victoria Mieses Perez ',
    'Claudio Almonte Chevalier',
    'Khalil Evelio Quezada Hernandez',
    'Jean Paul Vergez Evins',
    'Ysabelle Marie Rodriguez Alvarez ',
    'Ofir Limardo Solano Melia',
    'Maia A. Pimentel',
    'Lisbeth Diaz',
    'Laura Diaz',
    'Nicole Amelia Pimentel',
    'Liza Rosaury Pimentel',
    'Adlin Isabella Toribio Melgen',
    'Ian Santiago Toribio Melgan',
    'Leandro Montaño ',
    'Maria Brea',
    'Ana Camila Guillen ',
    'Scainer Eucebio de Jesus',
    'Albert Tejeda Rizik',
    'Yennifer Perla Rivas Sanchez',
    'Francis Camila Gomez Rodriguez',
    'Mya Ramirez Guzmán ',
    'Nicole Marie de Castro Reynoso',
    'Andy Comas Gonzalez',
    'Mariela del Carmen Almanzar Capestany',
    'Rosina Maria Hernandez Vallejo',
    'Luis Mario Gomez',
    'Mervin Francisco Luzón Castillo',
    'Samantha Aimee Richardson Troncoso',
    'Nicole NG Cruz',
    'Gabriela Marie Hidalgo Peguero',
    'Daniel Riopedre Perez',
    'Angela Cristina Riopedre perez',
    'Luis Manuel Riopedre Perez',
    'Lia Genao R',
    'Yeuri Agramonte S',
    'Nicole Marie Suriel Alvarez',
    'Mia Georgina de Pool de la Rosa',
    'Harold Ulises Garcia Morillo',
    'samuel Alexandro Amador Paulino',
    'Adrian Josue Gamboa Albornoz',
    'Anibelca Marie Feliz Concepcion ',
    'Isabella Gonzalez Tiburcio',
    'Manuel Sierra Lopez',
    'Patricia Garcia De Aza',
    'Mary Anne Guerrero Perez',
    'Belmary Montero Delgado',
    'Frayniel Andujar Valerio',
    'Diego Hugo Lavandier',
    'Heilie Laura Sanchez Grullon',
    'Anel Sofia Joa Perez',
    'Miguel A Concepcion Lora',
    'Dayshlen M de Aza Rodriguez',
    'Isabelle Marie Peña Martinez',
    'Ramon Antonio Vasquez Tejada',
    'Alejandro Jimenez Camacho',
    'Adrien Alexis Van Mackhoven',
    'Camila Moreta ',
    'Enmanuel Molina Abreu',
    'Kevin Omar Sanchez Checo',
    'Samantha M. Diaz Batista',
    'Karla Elena Aquino Frias',
    'Carlos Rafael de Leon Dominguez',
    'Julianna Maria Nuñez Velez',
    'Jorge Gabriel Guillen Lorenzo',
    'Yareth Velez Portorreal',
    'Camila Rueda Verez',
    'Isleiny Shanelly Carrion Manzanillo',
    'Eduardo Morillo',
    'Sofia Morillo',
    'Sofia Isabella Marquez Rodriguez',
    'Lara Marie Veras ',
    'Lisa Marie Veras ',
    'Maria Jose Garcia Liz',
    'Margaret Garcia Liz',
    'Escaria Acosta',
    'Denisse Quezada Doran',
    'Steven Quezada Duran',
    'Lisbeth Marie Perez Estevez',
    'Marivi Yireh Castaño Beato',
    'Ian Ernesto Rodriguez Castillo',
    'Lia Desiree Rodriguez',
    'Elian Alexis Severino',
    'Amelia Marie Severino',
    'Carlos Vargas',
    'Miguel Angel Vargas ',
    '-----',
    'Matias Portilla',
    'Wendy Carolina Pontilla',
    'Kevin Arturo Zorrilla Peña',
    'dktoribio@gmail.com',
    'Tomas Efrain Polanco Hernandez',
    'Amanda Elide Gomez Amador',
    'Mariel Esperanza Zorrilla Peña',
    'Ana Lucila Guzman Diaz',
    'Luisa Maria Cabrera Solano',
    'Kimberly Nuñez Ramirez',
    'Joaquin Jara Zambrano',
    'Diego Jose Herrera Sanchez',
    'Carolaine Michell Reyes Soto',
    'Sophia Paunovic Victoria',
    'Norelis Milagros Reyes Sanchez',
    'Irlanda Yoigt',
    'Jadiel Enrique Matos Rosario',
    'Anthony Junior Perez Rojas',
    'Denisse Rachely Feliz Peña',
    'Marjorie Feliz Peña',
    'Jessica Valdez',
    'Enmanuel Jimenez Castillo',
    'Samuel jimenez Castillo',
    'Wander Emir Garcia ',
    'Kimberly Samboy',
    'Esteben Moise privitera',
    'Alannis Antigua',
    'Gabriela Ventura',
    'Adrian Peña Castro',
    'Camille Alejandra Jeaños Veriguete',
    'Diego de jesus Rodriguez',
    'alnaldo Emmanuel Matos Hamilton',
    'Yonard Yandier Ramirez',
    'Angelica Camila Valdez Grullon',
    'Marcos Moreno',
    'Miguel Angel Soto Salas',
    'Maria Quezada',
    'Estefania Espinosa',
    'Edward Almonte Batista',
    'Samuel Osvaldo Mota Soto',
    'Ruth Marie Mota Soto'
]

ids = []

for name in student_names:
    # print(query.format(name))
    cursor.execute(query.format(name))
    result = cursor.fetchall()
    try:
        id = result[0][0]
    except Exception:
        continue
    if id != "" and id != None:
        ids.append(id)

with open('emails.txt','w+') as my_file:
    for id in ids:
        my_file.write(id + '\n')